// <auto-generated />
using System;
using CodeFirstExercise.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirstExercise.Migrations
{
    [DbContext(typeof(TrapSampleContext))]
    partial class TrapSampleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeFirstExercise.Context.Specimen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<string>("Species")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrapSampleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrapSampleId");

                    b.ToTable("Specimens");
                });

            modelBuilder.Entity("CodeFirstExercise.Context.TrapSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Analyst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Collection")
                        .HasColumnType("datetime2");

                    b.Property<string>("Collector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TrapSamples");
                });

            modelBuilder.Entity("CodeFirstExercise.Context.Specimen", b =>
                {
                    b.HasOne("CodeFirstExercise.Context.TrapSample", null)
                        .WithMany("Contents")
                        .HasForeignKey("TrapSampleId");
                });
#pragma warning restore 612, 618
        }
    }
}
